"""A model: its variables, its constraints and the matrix they assemble into."""

from collections.abc import Iterable, Mapping
from typing import TYPE_CHECKING, Any

import numpy as np
import numpy.typing as npt

from nimopt.absence import Absence, Recorder
from nimopt.assembly import Assembled, Written, assemble_model, matrix_of
from nimopt.coefficient import Coefficient
from nimopt.constraint import Constraint, narrow
from nimopt.explanation import (
    ConstraintShape,
    Explanation,
    objective_constant,
    objective_text,
    param_shape,
    piecewise_shape,
    set_shape,
    variable_shape,
)
from nimopt.param import Param
from nimopt.piecewise import Piecewise, check_not_generated, generate
from nimopt.row import Row, written
from nimopt.session import Session
from nimopt.sets import Alias
from nimopt.solvers.base import check_sense
from nimopt.symbol import read_at_its_sets
from nimopt.syntax import render
from nimopt.term import Expression
from nimopt.variable import Variable

if TYPE_CHECKING:
    from nimopt.solution import Solution


def objective_expression(expression: Any) -> Expression:
    """Return `expression` as an objective, read at its sets.

    Raises TypeError for a value that is not an expression, and ValueError for
    an expression with free dimensions.
    """
    expression = read_at_its_sets(expression)
    if not isinstance(expression, Expression):
        raise TypeError(
            f"an objective is an expression over the model's columns; got "
            f"{type(expression).__name__}"
        )
    if expression.frame:
        raise ValueError(
            f"objective expression has free dimensions {expression.frame}; "
            f"sum the expression over them"
        )
    return expression


class Model:
    """Variables numbered into one column space, constraints into one matrix.

    A variable's columns are a contiguous range of that space, computed from
    its multi-index. Declaring a variable allocates its bounds and nothing per
    column.
    """

    def __init__(self, name: str = "model", sense: str = "min") -> None:
        check_sense(sense)
        self.name = str(name)
        self._sense = sense
        self.variables = {}
        self.constraints = {}
        self.piecewise_declarations = {}
        self._objective = None
        self._n_columns = 0
        self._n_rows = 0

    @property
    def sense(self) -> str:
        """Return the direction this model's objective is optimized in."""
        return self._sense

    @property
    def objective_constant(self) -> float:
        """Return the objective's fixed cost, zero where the objective has none."""
        return 0.0 if self._objective is None else self._objective.constant

    @property
    def objective(self) -> Any:
        """Return the expression the model's sense optimizes, or None."""
        return self._objective

    def __repr__(self) -> str:
        return (
            f"Model({self.name!r}, {len(self.variables)} variables, "
            f"{self.n_columns} columns, {self.n_rows} rows)"
        )

    @property
    def n_columns(self) -> int:
        """Return the number of columns declared."""
        return self._n_columns

    @property
    def n_rows(self) -> int:
        """Return the number of rows declared."""
        return self._n_rows

    @property
    def nnz(self) -> int:
        """Return the number of coefficients the assembled matrix contains."""
        return sum(c.nnz for c in self.constraints.values())

    def var(
        self,
        name: str,
        sets: Any,
        subset: Any = None,
        lower: float | Param = 0.0,
        upper: float | Param = np.inf,
        integer: bool = False,
    ) -> Variable:
        """Declare a variable over `sets`, or over `subset` of them.

        Raises ValueError for a name already declared as a variable or
        generated by a piecewise declaration. `Model` accepts any other
        name. `Definition.var` and `save` raise ValueError for a name an
        expression cannot address.
        """
        if name in self.variables:
            raise ValueError(
                f"variable {name!r} is already declared; declare another name"
            )
        check_not_generated(name, "variable", self.piecewise_declarations)
        variable = Variable(
            name,
            sets,
            start=self._n_columns,
            total_columns=self._n_columns,
            subset=subset,
            lower=lower,
            upper=upper,
            integer=integer,
        )
        self.variables[name] = variable
        self._n_columns += variable.n_columns
        self._renumber()
        return variable

    def _adopt(self, variable: Variable) -> None:
        if variable.name in self.variables:
            raise ValueError(
                f"variable {variable.name!r} is already declared; declare another name"
            )
        check_not_generated(variable.name, "variable", self.piecewise_declarations)
        variable._bind(self._n_columns, self._n_columns)
        self.variables[variable.name] = variable
        self._n_columns += variable.n_columns
        self._renumber()

    def _renumber(self) -> None:
        """Set the column space's current size on every variable."""
        for variable in self.variables.values():
            variable.total_columns = self._n_columns

    def constraint(
        self, name: str, relation: Any, where: Any = None, over: Any = None
    ) -> Constraint:
        """Declare a constraint from a comparison of an expression.

        The relation is symbolic. The constraint stores the term list, not a
        block. `where=` takes a domain over the constraint's free dimensions
        and narrows its rows. `over=` takes one and declares the rows.
        """
        if name in self.constraints:
            raise ValueError(
                f"constraint {name!r} is already declared; declare another name"
            )
        check_not_generated(name, "constraint", self.piecewise_declarations)
        constraint = Constraint(name, relation, where, over)
        self.constraints[name] = constraint
        self._n_rows += constraint.n_rows
        return constraint

    def piecewise(
        self,
        name: str,
        x: Any,
        x_points: Any,
        y: Any,
        y_points: Any,
        sign: str,
        method: str,
        active: Any = None,
        relaxed: bool = False,
        where: Any = None,
    ) -> Piecewise:
        """Declare a piecewise-linear relation of `y` to `x` and its rows.

        `x` lies on the curve through `x_points` and `y_points`, and `sign`
        relates `y` to the curve. `method` is "incremental", "tangent" or
        "auto". "auto" generates "tangent" where it applies and "incremental"
        otherwise. `Piecewise.formulation` reports the method generated.
        `active` scales the curve of the incremental method to zero, and
        requires a binary variable unless `relaxed` is True. `where`
        restricts the declaration to the entities at its coordinates. The
        generated variables and constraints are declarations of this model.
        The checks run before any declaration. Raises ValueError for a name
        already declared, for a generated name the model declares, for an
        argument `Piecewise` rejects and for breakpoints that fail a check.
        """
        name = str(name)
        if name in self.piecewise_declarations:
            raise ValueError(
                f"piecewise {name!r} is already declared; declare another name"
            )
        declaration = Piecewise(
            name, x, x_points, y, y_points, sign, method, active, relaxed, where
        )
        generated = generate(
            declaration, self._declared_names(), f"model {self.name!r}"
        )
        for variable in generated.variables:
            self._adopt(variable)
        for constraint_name, relation in generated.constraints:
            self.constraint(constraint_name, relation)
        self.piecewise_declarations[name] = declaration
        return declaration

    def _generated(self) -> frozenset[str]:
        """Return every name this model's piecewise declarations generated."""
        names = set()
        for declaration in self.piecewise_declarations.values():
            names |= declaration.generated_names()
        return frozenset(names)

    def _declared_names(self) -> set[str]:
        """Return every set, parameter, variable and constraint name of this model."""
        parameters = self._parameters()
        sets, aliases = self._dimensions(parameters)
        return {
            *self.variables,
            *self.constraints,
            *(p.name for p in parameters),
            *(s.name for s in (*sets, *aliases)),
        }

    def set_objective(self, expression: Any) -> None:
        """Set the objective the model's sense optimizes.

        A constant in the expression is a fixed cost. It adds no column, and
        the solved objective reports it beside the solver's value.
        """
        self._objective = objective_expression(expression)

    def objective_coefficients(self) -> npt.NDArray[np.float64]:
        """Return one cost per column, zero where the objective has no term.

        The objective materialises here, not where it is set. Its column
        dimension spans every column the model declares, including those
        declared after it.
        """
        if self._objective is None:
            return np.zeros(self._n_columns, dtype=np.float64)
        self._renumber()
        block, _ = self._objective.materialise()
        return block.to_dense()

    def column_bounds(
        self,
    ) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.float64]]:
        """Return the `(lower, upper)` bound of every column."""
        lower = np.empty(self._n_columns, dtype=np.float64)
        upper = np.empty(self._n_columns, dtype=np.float64)
        for variable in self.variables.values():
            variable.write_bounds(lower, upper)
        return lower, upper

    def integrality(self) -> npt.NDArray[np.int32]:
        """Return one flag per column, 1 where its variable is integer."""
        flags = np.zeros(self._n_columns, dtype=np.int32)
        for variable in self.variables.values():
            if variable.integer:
                flags[variable._columns()] = 1
        return flags

    def explain(self) -> Explanation:
        """Return what this model built, its declarations each with its count.

        A model contains variables and constraints. Its sets and parameters
        are read out of them and reported in order of first appearance.
        """
        parameters = self._parameters()
        dimensions, aliases = self._dimensions(parameters)
        return Explanation(
            name=self.name,
            sense=self.sense,
            built=True,
            sets=tuple(set_shape(s, len(s)) for s in dimensions),
            aliases=tuple((a.name, a.base.name) for a in aliases),
            parameters=tuple(param_shape(p, p.nnz) for p in parameters),
            variables=tuple(
                variable_shape(name, v, v.n_columns)
                for name, v in self.variables.items()
            ),
            constraints=tuple(
                ConstraintShape(
                    name, c.frame, c.sense, c.n_rows, c.nnz, render(c.relation)
                )
                for name, c in self.constraints.items()
            ),
            objective=objective_text(self._objective),
            objective_constant=objective_constant(self._objective),
            columns=self._n_columns,
            rows=self._n_rows,
            nonzeros=self.nnz,
            piecewise=tuple(
                piecewise_shape(d) for d in self.piecewise_declarations.values()
            ),
        )

    def _variable(self, name: str, other: str | None = None) -> Variable:
        """Return the named variable.

        Raises KeyError for a name that is not a declared variable. The message
        lists the declared variables. `other` is the action the message gives
        where `name` is a constraint.
        """
        if name in self.variables:
            return self.variables[name]
        valid = (
            f"use one of {tuple(self.variables)}"
            if self.variables
            else "declare a variable first"
        )
        if name in self.constraints:
            raise KeyError(
                f"{name!r} is a constraint, not a variable; {other or valid}"
            )
        raise KeyError(f"model {self.name!r} has no variable {name!r}; {valid}")

    def _constraint(self, name: str) -> Constraint:
        """Return the named constraint.

        Raises KeyError for a name that is not a declared constraint. The
        message lists the declared constraints.
        """
        if name in self.constraints:
            return self.constraints[name]
        valid = (
            f"use one of {tuple(self.constraints)}"
            if self.constraints
            else "declare a constraint first"
        )
        if name in self.variables:
            raise KeyError(f"{name!r} is a variable, not a constraint; {valid}")
        raise KeyError(f"model {self.name!r} has no constraint {name!r}; {valid}")

    def row(self, name: str, **coords: Any) -> "Row":
        """Return one row of this model's matrix, at the coordinate given.

        The row is written by the pass `assemble` runs, for the named
        constraint alone, and is the row the solver is given. Its index is its
        position in the assembled matrix. Raises KeyError for a name that is
        not a declared constraint. Raises ValueError for a label that is not a
        member of its dimension. Raises ValueError for a coordinate the
        constraint has no row at; the message refers to `absent`.
        """
        constraint = self._constraint(name)
        position = constraint.position_of(coords)
        matrix, _, lower, upper = matrix_of(
            {name: constraint}, self._n_columns, Written(None, 0, "")
        )
        indices, values, indptr = matrix.to_csr()
        names = tuple(self.constraints)
        start = sum(self.constraints[n].n_rows for n in names[: names.index(name)])
        span = slice(indptr[position], indptr[position + 1])
        return written(
            self,
            name,
            start + position,
            position,
            indices[span],
            values[span],
            float(lower[position]),
            float(upper[position]),
        )

    def absent(self, name: str) -> "Absence":
        """Return which coordinates fell out of the named constraint, and why.

        A dropped row leaves no trace in the matrix. This runs that one
        constraint's shape pass again with a recorder attached. The model and
        the rows already built are unchanged. Raises KeyError for a name that
        is not a declared constraint.
        """
        constraint = self._constraint(name)
        record = Recorder()
        narrow(constraint, record)
        return record.absence(name)

    def _parameters(self, as_declared: bool = False) -> tuple[Param, ...]:
        """Return every parameter this model reads, in order of first appearance.

        A derived coefficient is walked into. An objective over an arithmetic
        of two parameters reports both, with the sets they introduce.
        `as_declared=True` skips what the piecewise declarations generated and
        reads the parameters of each piecewise declaration.
        """
        found = {}

        def take(held: Any) -> None:
            if isinstance(held, Coefficient):
                leaves = held.parameters()
            else:
                leaves = (held,) if isinstance(held, Param) else ()
            for parameter in leaves:
                if found.setdefault(parameter.name, parameter) is not parameter:
                    raise ValueError(
                        f"model {self.name!r} reads two parameters named "
                        f"{parameter.name!r}; declare one parameter per name"
                    )

        skip = self._generated() if as_declared else frozenset()
        for name, variable in self.variables.items():
            if name in skip:
                continue
            for held in (variable.lower, variable.upper, variable.subset):
                take(held)
        for name, constraint in self.constraints.items():
            if name in skip:
                continue
            for term in constraint.expression.terms:
                if term.coefficient is not None:
                    take(term.coefficient)
            take(constraint.rhs)
            take(constraint.where)
            take(constraint.over)
        if as_declared:
            for declaration in self.piecewise_declarations.values():
                for expression in (declaration.x, declaration.y, declaration.active):
                    for term in () if expression is None else expression.terms:
                        if term.coefficient is not None:
                            take(term.coefficient)
                take(declaration.x_points)
                take(declaration.y_points)
                take(declaration.where)
        if self._objective is not None:
            for term in self._objective.terms:
                if term.coefficient is not None:
                    take(term.coefficient)
        return tuple(found.values())

    def _dimensions(
        self, parameters: Iterable[Param], as_declared: bool = False
    ) -> tuple[tuple[Any, ...], tuple[Alias, ...]]:
        """Return the sets and the aliases this model is declared over, in order.

        A dimension a coefficient introduces belongs to no variable, and the
        parameters are walked beside the variables. An alias reads a set's
        members and has none of its own. The two are reported apart, and a
        file contains data for a set alone. The base set of an alias is taken
        with the alias. `as_declared=True` skips the variables the piecewise
        declarations generated.
        """
        found = {}

        def take(dimension: Any) -> None:
            if isinstance(dimension, Alias):
                take(dimension.base)
            if found.setdefault(dimension.name, dimension) is not dimension:
                raise ValueError(
                    f"model {self.name!r} is declared over two sets named "
                    f"{dimension.name!r}; declare one set per name"
                )

        skip = self._generated() if as_declared else frozenset()
        for name, variable in self.variables.items():
            if name in skip:
                continue
            for dimension in variable.sets:
                take(dimension)
        for parameter in parameters:
            for dimension in parameter.sets:
                take(dimension)
        held = tuple(found.values())
        return (
            tuple(d for d in held if not isinstance(d, Alias)),
            tuple(d for d in held if isinstance(d, Alias)),
        )

    def assemble(self, progress: Any = False) -> Assembled:
        """Return the model's matrix and its row and column data, in CSR form.

        Each constraint rebuilds its expression, writes it into its slice of
        one buffer and releases it. One expression is live at a time.
        """
        return assemble_model(self, progress)

    def session(
        self,
        solver: str = "highs",
        options: Mapping[str, Any] | None = None,
        progress: Any = False,
    ) -> "Session":
        """Return an open session on this model, for a solve and what follows.

        The matrix is assembled when the session opens. The solver's model is
        kept afterwards, and a conflict is read from the solved instance.
        """
        return Session(self, solver, options, progress)

    def solve(
        self,
        solver: str = "highs",
        options: Mapping[str, Any] | None = None,
        progress: Any = False,
    ) -> "Solution":
        """Assemble the model, solve it, and read the values back onto its sets.

        `options` gives the solver's settings under the names `options()`
        reports. `log=True` among them has the solver write its own iteration
        log. `progress=` reports the assembly. The assembly finishes before
        the solver starts.
        """
        with self.session(solver, options, progress) as session:
            return session.solve()
